### ISSUE TITLE
error in installation

### ISSUE THREAD

**Issue by ahcyip** [AndreaCirilloAC/paletter#10]
Hi, 
Do you know about this error in installation, or is it a problem with my computer/system?

> devtools::install_github("AndreaCirilloAC/paletter")
Downloading GitHub repo AndreaCirilloAC/paletter@HEAD
√  checking for file 'C:\Users\ayip\AppData\Local\Temp\1\RtmpGoKPcK\remotes49ec24b755c7\AndreaCirilloAC-paletter-d9d45e4/DESCRIPTION' ...
-  preparing 'paletter': (542ms)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'paletter_0.0.0.9000.tar.gz'
   
Installing package into ‘C:/Users/ayip/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'paletter' ...
** using staged installation
** R
** data
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'dplyr' was built under R version 3.6.3
Execution halted
ERROR: lazy loading failed for package 'paletter'
* removing 'C:/Users/ayip/Documents/R/win-library/3.6/paletter'
Error: Failed to install 'paletter' from GitHub:
  (converted from warning) installation of package ‘C:/Users/ayip/AppData/Local/Temp/1/RtmpGoKPcK/file49ec11a212d4/paletter_0.0.0.9000.tar.gz’ had non-zero exit status

**Comment by mbojan** [comment]
This is not a paletter error. You have an old version of R and  old version of dplyr package. I suggest you update both.

**Comment by ahcyip** [comment]
Thanks. I will update everything.
