### ISSUE TITLE
misspelling of "continuous"

### ISSUE THREAD

**Issue by neilfws** [AndreaCirilloAC/paletter#6]
`optimize_palette.R` contains the line:

      }else if ( type_of_variable == "continous"){

The correct spelling is "continuous". This will confuse users when they spell it correctly and the code throws an error.

(by the way this is a great package! thanks for creating it)

**Comment by AndreaCirilloAC** [comment]
Hi @neilfws thank you for taking the time to highlight this.
I will try to fix it asap, in the meanwhile I you would like to create a Pull request fixing the typo I would be really pleased to accept it.

Thank you anyway

**Comment by neilfws** [comment]
OK, pull request created.
